### ISSUE TITLE
[Usersnap] intro to whiteboarding link on oct 2023 syllabus leads to this page not found

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/javascript-full-stack#17]
Usersnap feedback [5079](https://app.usersnap.com/l/feedback/cdf986b1-7827-4b25-b583-9bd41a1e1ca1?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://www.learnhowtoprogram.com/intermediate-javascript/object-oriented-javascript/introduction-to-whiteboarding

Text: intro to whiteboarding link on oct 2023 syllabus leads to this page not found

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/31b47a06-b2db-43de-8604-48c92a2159b2-annotated_055e4cd4-4a1f-4daa-ae94-07efe7d849ee.png?etag=1fafde4f4ecfee56b7d9da2b47f72da8

**Comment by CalvinPVIII** [comment]
this was an issue related to the syllabus and not the curriculum.  The link on the syllabus has been updated.
