### ISSUE TITLE
[Usersnap] Intro to whiteboarding from our google docs syllabus opens this "page not found"

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/javascript-full-stack#9]
Usersnap feedback [5065](https://app.usersnap.com/l/feedback/bfc20a46-6d8f-4448-918d-8b981dfd9e05?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://www.learnhowtoprogram.com/intermediate-javascript/object-oriented-javascript/introduction-to-whiteboarding

Text: Intro to whiteboarding from our google docs syllabus opens this "page not found"

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/8129044a-8b25-4f96-954e-204a2a59ad1f-annotated_bfa513ea-0a36-4f42-87cc-28dfd3d7f21c.png?etag=96eb9de579ad5b4623281e57190a5efe

**Comment by CalvinPVIII** [comment]
this was an issue related to the syllabus and not the curriculum.  The link on the syllabus has been updated.
